### ISSUE TITLE
Ubuntu 18.04 version

### ISSUE THREAD

**Issue by colinodell** [geerlingguy/packer-drupal-vm#2]
Do you have any plans to create a version of this based on Ubuntu 18.04?  It would be great to have the [speed improvements](https://github.com/geerlingguy/drupal-vm/issues/1774#issuecomment-440785815) this box provides but with 18.04 as its base OS.

**Comment by geerlingguy** [comment]
Yep; related https://github.com/geerlingguy/drupal-vm/issues/1881

**Comment by geerlingguy** [comment]
The initial version running 18.04 will be box tag 2.0.0.

**Comment by geerlingguy** [comment]
2.0.0 box version has ubuntu 18.04 base: https://app.vagrantup.com/geerlingguy/boxes/drupal-vm/versions/2.0.0
